import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'

const nunito = Nunito({
	variable: '--font-nunito',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

interface RootLayoutProps {
	children: React.ReactNode
}

const RootLayout = ({ children }: RootLayoutProps) => {
	return (
		<ClerkProvider afterSignOutUrl="/">
			<html lang="en">
				<body
					className={`${nunito.className} antialiased`}
				>
					{children}
				</body>
			</html>
		</ClerkProvider>
	)
}
export default RootLayout
